/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import javax.swing.ListSelectionModel;

/**
 *
 * @author dario
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantallaInicio = new javax.swing.JPanel();
        txtLogin = new javax.swing.JLabel();
        login = new javax.swing.JPanel();
        btnIniciarSesion = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        registrarUsuario = new javax.swing.JPanel();
        fieldApellidos = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        btnRegistrarUsuario = new javax.swing.JButton();
        txtRegistrarUsuario = new javax.swing.JLabel();
        txtRegistrarUsuario.setOpaque(true);
        txtCorreo = new javax.swing.JLabel();
        fieldCorreo = new javax.swing.JTextField();
        volverRegistroUsuario = new javax.swing.JButton();
        iniciarSesion = new javax.swing.JPanel();
        fieldContraseña = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        fieldUsuario = new javax.swing.JTextField();
        btnIniciar = new javax.swing.JButton();
        txtIniciarSesion = new javax.swing.JLabel();
        txtIniciarSesion.setOpaque(true);
        volverIniciarSesion = new javax.swing.JButton();
        pantallaJuego = new javax.swing.JPanel();
        txtOpcionesJuego = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnUnirsePartida = new javax.swing.JButton();
        txtPantallaInicio = new javax.swing.JLabel();
        btnCrearPartida = new javax.swing.JButton();
        ranking = new javax.swing.JPanel();
        txtRankingUsuarios = new javax.swing.JLabel();
        panelRanking = new javax.swing.JScrollPane();
        tablaRanking = new javax.swing.JTable();
        backBtnRanking = new javax.swing.JButton();
        crearPartida = new javax.swing.JPanel();
        btnCrearPartidaNueva = new javax.swing.JButton();
        nombrePartida = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        colorFichaJ1 = new javax.swing.JComboBox<>();
        colorFichaJ2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        numColumnas = new javax.swing.JComboBox<>();
        numFilas = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        backBtnCrearPartida = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        unirsePartida = new javax.swing.JPanel();
        btnIniciarJuego = new javax.swing.JButton();
        backBtnUP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPartidas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pantallaInicio.setBackground(new java.awt.Color(249, 248, 248));
        pantallaInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLogin.setBackground(new java.awt.Color(57, 160, 237));
        txtLogin.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtLogin.setText("              Login");
        txtLogin.setOpaque(true);
        pantallaInicio.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 1920, 65));

        login.setBackground(new java.awt.Color(249, 248, 248));
        login.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciarSesion.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        login.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 240, 250, -1));

        btnRegistrar.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        btnRegistrar.setText("Registrar");
        login.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 360, 250, -1));

        pantallaInicio.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 235, 690, 670));

        registrarUsuario.setBackground(new java.awt.Color(249, 248, 248));
        registrarUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.white));
        registrarUsuario.setVisible(false);
        registrarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fieldApellidos.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        registrarUsuario.add(fieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 340, 40));

        txtApellidos.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtApellidos.setText("Apellidos:");
        registrarUsuario.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        txtNombre.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtNombre.setText("Nombre:");
        registrarUsuario.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        fieldNombre.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        registrarUsuario.add(fieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 340, 40));

        btnRegistrarUsuario.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        btnRegistrarUsuario.setText("Registrar");
        registrarUsuario.add(btnRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 230, -1));

        txtRegistrarUsuario.setBackground(new java.awt.Color(151, 85, 161));
        txtRegistrarUsuario.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtRegistrarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtRegistrarUsuario.setText("Registro de usuarios");
        registrarUsuario.add(txtRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 690, -1));

        txtCorreo.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtCorreo.setText("Correo:");
        registrarUsuario.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        fieldCorreo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        registrarUsuario.add(fieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 340, 40));

        volverRegistroUsuario.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        volverRegistroUsuario.setText("<");
        registrarUsuario.add(volverRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

        pantallaInicio.add(registrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 235, 690, 670));

        iniciarSesion.setBackground(new java.awt.Color(249, 248, 248));
        iniciarSesion.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.white));
        iniciarSesion.setVisible(false);
        iniciarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        iniciarSesion.add(fieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 340, 40));

        txtContraseña.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtContraseña.setText("Contraseña:");
        iniciarSesion.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtUsuario.setText("Usuario:");
        iniciarSesion.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        iniciarSesion.add(fieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 340, 40));

        btnIniciar.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        btnIniciar.setText("Iniciar Sesión");
        iniciarSesion.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 290, -1));

        txtIniciarSesion.setBackground(new java.awt.Color(151, 85, 161));
        txtIniciarSesion.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        txtIniciarSesion.setText("Iniciar Sesión");
        iniciarSesion.add(txtIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 690, -1));

        volverIniciarSesion.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        volverIniciarSesion.setText("<");
        iniciarSesion.add(volverIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

        pantallaInicio.add(iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 235, 690, 670));

        getContentPane().add(pantallaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pantallaJuego.setBackground(new java.awt.Color(255, 255, 255));
        pantallaJuego.setVisible(false);
        pantallaJuego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOpcionesJuego.setBackground(new java.awt.Color(57, 160, 237));
        txtOpcionesJuego.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        txtOpcionesJuego.setForeground(new java.awt.Color(255, 255, 255));
        txtOpcionesJuego.setText("Opciones del juego");
        txtOpcionesJuego.setOpaque(true);
        pantallaJuego.add(txtOpcionesJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 440, 65));

        btnCerrarSesion.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        pantallaJuego.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 670, 390, -1));

        btnUnirsePartida.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        btnUnirsePartida.setText("Unirse a una Partida");
        pantallaJuego.add(btnUnirsePartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, 390, -1));

        txtPantallaInicio.setBackground(new java.awt.Color(57, 160, 237));
        txtPantallaInicio.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        txtPantallaInicio.setForeground(new java.awt.Color(255, 255, 255));
        txtPantallaInicio.setText("               Pantalla de inicio");
        txtPantallaInicio.setOpaque(true);
        pantallaJuego.add(txtPantallaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 1920, 65));

        btnCrearPartida.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        btnCrearPartida.setText("Crear Partida");
        btnCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPartidaActionPerformed(evt);
            }
        });
        pantallaJuego.add(btnCrearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 560, 390, -1));

        getContentPane().add(pantallaJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        ranking.setBackground(new java.awt.Color(255, 255, 255));
        ranking.setVisible(false);
        ranking.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRankingUsuarios.setBackground(new java.awt.Color(57, 160, 237));
        txtRankingUsuarios.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        txtRankingUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        txtRankingUsuarios.setText("                  Ranking de usuarios");
        txtRankingUsuarios.setOpaque(true);
        ranking.add(txtRankingUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 1920, 65));

        panelRanking.setBackground(new java.awt.Color(255, 255, 255));

        tablaRanking.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        tablaRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre del jugador", "Partidas Ganadas", "Partidas Perdidas"
            }
        ));
        panelRanking.setViewportView(tablaRanking);

        ranking.add(panelRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 1760, 650));

        backBtnRanking.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        backBtnRanking.setText("<");
        ranking.add(backBtnRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(ranking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        crearPartida.setBackground(new java.awt.Color(255, 255, 255));
        crearPartida.setVisible(false);
        crearPartida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrearPartidaNueva.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnCrearPartidaNueva.setText("Crear Partida");
        crearPartida.add(btnCrearPartidaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 850, 210, 70));

        nombrePartida.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        crearPartida.add(nombrePartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 350, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setText("Color J2");
        crearPartida.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 110, 30));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel3.setText("Nombre de la partida:");
        crearPartida.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 270, 30));

        colorFichaJ1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        colorFichaJ1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Azul", "Amarillo", "Verde" }));
        crearPartida.add(colorFichaJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 100, 30));

        colorFichaJ2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        colorFichaJ2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Azul", "Amarillo", "Verde" }));
        crearPartida.add(colorFichaJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 100, 30));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel5.setText("Color J1");
        crearPartida.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 150, 30));

        numColumnas.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        numColumnas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9", "10", "11" }));
        crearPartida.add(numColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 650, 110, 30));

        numFilas.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        numFilas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11" }));
        crearPartida.add(numFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 650, 110, 30));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel6.setText("Columnas:");
        crearPartida.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 600, 150, 30));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel7.setText("Filas:");
        crearPartida.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 600, 90, 30));

        backBtnCrearPartida.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        backBtnCrearPartida.setText("<");
        crearPartida.add(backBtnCrearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(238, 238, 238));
        jSeparator1.setForeground(new java.awt.Color(238, 238, 238));
        crearPartida.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 580, 510, 10));

        jSeparator2.setBackground(new java.awt.Color(238, 238, 238));
        jSeparator2.setForeground(new java.awt.Color(238, 238, 238));
        crearPartida.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 510, 10));

        getContentPane().add(crearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        unirsePartida.setVisible(false);
        unirsePartida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciarJuego.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        btnIniciarJuego.setText("Unirse");
        btnIniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarJuegoActionPerformed(evt);
            }
        });
        unirsePartida.add(btnIniciarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 910, 200, 50));

        backBtnUP.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        backBtnUP.setText("<");
        unirsePartida.add(backBtnUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        listaPartidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(listaPartidas);

        unirsePartida.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 1730, 700));

        getContentPane().add(unirsePartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnIniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarJuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarJuegoActionPerformed

    private void btnCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearPartidaActionPerformed
public void conectaControlador(Controlador c) {
        //Comando mostrar panel iniciar sesion
        btnIniciarSesion.addActionListener(c);
        btnIniciarSesion.setActionCommand("PANEL_INICIAR_SESION");

        //Comando mostrar panel registrar
        btnRegistrar.addActionListener(c);
        btnRegistrar.setActionCommand("PANEL_REGISTRAR");

        //Comando para registrar usuario
        btnRegistrarUsuario.addActionListener(c);
        btnRegistrarUsuario.setActionCommand("REGISTRAR_USUARIO");

        //Comando para el boton para regresar al menu de login
        volverRegistroUsuario.addActionListener(c);
        volverRegistroUsuario.setActionCommand("VOLVER_REGISTRO_USUARIO");

        //Comando para Iniciar sesion
        btnIniciar.addActionListener(c);
        btnIniciar.setActionCommand("INICIAR_SESION");
        
        //Comando para volver al login desde iniciar sesion
        volverIniciarSesion.addActionListener(c);
        volverIniciarSesion.setActionCommand("VOLVER_INICIAR_SESION");    
        
        //Comando para crear partida
        btnCrearPartidaNueva.addActionListener(c);
        btnCrearPartidaNueva.setActionCommand("CREAR_PARTIDA");
        
        //Comando para abrir panel partida
        btnCerrarSesion.addActionListener(c);
        btnCerrarSesion.setActionCommand("PANEL_CREAR_PARTIDA");
        
        //Panel crearPartida
        btnCrearPartida.addActionListener(c);
        btnCrearPartida.setActionCommand("PANEL_CREAR_PARTIDA");
        
        //Comando para salir de crear partida
        backBtnCrearPartida.addActionListener(c);
        backBtnCrearPartida.setActionCommand("VOLVER_CREAR_PARTIDA");
        
        //Comando para unirse a una partida
        btnUnirsePartida.addActionListener(c);
        btnUnirsePartida.setActionCommand("UNIRSE_PARTIDA");
        
        //Comando para cerrar sesion
        btnCerrarSesion.addActionListener(c);
        btnCerrarSesion.setActionCommand("CERRAR_SESION");
//        //Comando pra 
//        btnIniciarJuego.addActionListener(c);
//        btnIniciarJuego.setActionCommand("VERIFICAR_INICIO");
        
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton backBtnCrearPartida;
    public javax.swing.JButton backBtnRanking;
    public javax.swing.JButton backBtnUP;
    javax.swing.JButton btnCerrarSesion;
    javax.swing.JButton btnCrearPartida;
    public javax.swing.JButton btnCrearPartidaNueva;
    public javax.swing.JButton btnIniciar;
    javax.swing.JButton btnIniciarJuego;
    public javax.swing.JButton btnIniciarSesion;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JButton btnRegistrarUsuario;
    javax.swing.JButton btnUnirsePartida;
    public javax.swing.JComboBox<String> colorFichaJ1;
    public javax.swing.JComboBox<String> colorFichaJ2;
    public javax.swing.JPanel crearPartida;
    public javax.swing.JTextField fieldApellidos;
    public javax.swing.JTextField fieldContraseña;
    public javax.swing.JTextField fieldCorreo;
    public javax.swing.JTextField fieldNombre;
    public javax.swing.JTextField fieldUsuario;
    public javax.swing.JPanel iniciarSesion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTable listaPartidas;
    public javax.swing.JPanel login;
    public javax.swing.JTextField nombrePartida;
    public javax.swing.JComboBox<String> numColumnas;
    public javax.swing.JComboBox<String> numFilas;
    private javax.swing.JScrollPane panelRanking;
    public javax.swing.JPanel pantallaInicio;
    public javax.swing.JPanel pantallaJuego;
    public javax.swing.JPanel ranking;
    public javax.swing.JPanel registrarUsuario;
    private javax.swing.JTable tablaRanking;
    private javax.swing.JLabel txtApellidos;
    private javax.swing.JLabel txtContraseña;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtIniciarSesion;
    private javax.swing.JLabel txtLogin;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtOpcionesJuego;
    private javax.swing.JLabel txtPantallaInicio;
    private javax.swing.JLabel txtRankingUsuarios;
    private javax.swing.JLabel txtRegistrarUsuario;
    private javax.swing.JLabel txtUsuario;
    public javax.swing.JPanel unirsePartida;
    public javax.swing.JButton volverIniciarSesion;
    public javax.swing.JButton volverRegistroUsuario;
    // End of variables declaration//GEN-END:variables
}
