/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author dario
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public Vista() {
        this.setUndecorated(true);
        this.setResizable(false);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionarArchivoXML = new javax.swing.JFileChooser();
        seleccionarImagen = new javax.swing.JFileChooser();
        menuPrincipal = new javax.swing.JPanel();
        banner = new javax.swing.JPanel();
        txtMenuPrincipal = new javax.swing.JLabel();
        txtJugar = new javax.swing.JLabel();
        Image image = null;
        Image mostrarPersonaje = null;
        try{
            image = ImageIO.read(new File(getImagePath("btn1",".png")));
            image = image.getScaledInstance(560 ,160, Image. SCALE_SMOOTH);
            mostrarPersonaje = ImageIO.read(new File(getImagePath("MarcoPersonaje3",".png")));
            mostrarPersonaje = mostrarPersonaje.getScaledInstance(540 ,450, Image. SCALE_SMOOTH);
        }catch(Exception e){
            System.out.println("Something went wrong.");
        }
        btnJugar = new JLabel(new ImageIcon(image));
        txtAgregarPersonajes = new javax.swing.JLabel();
        btnAgregarPersonaje = new JLabel(new ImageIcon(image));
        txtGestionCiudad = new javax.swing.JLabel();
        btnGestionCiudad = new JLabel(new ImageIcon(image));
        txtConsultas = new javax.swing.JLabel();
        btnConsultas = new JLabel(new ImageIcon(image));
        exitButton = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        agregarPersonaje = new javax.swing.JPanel();
        backBtnAP = new javax.swing.JLabel();
        txtAgregarHeroe = new javax.swing.JLabel();
        btnAgregarHeroe = new JLabel(new ImageIcon(image));
        txtAgregarAntiheroe = new javax.swing.JLabel();
        txtAgrergarVillano = new javax.swing.JLabel();
        btnAgregarVillano = new JLabel(new ImageIcon(image));
        btnAgregarAntiheroe = new JLabel(new ImageIcon(image));
        fondoAgregarPersonaje = new javax.swing.JLabel();
        agregarHeroe = new javax.swing.JPanel();
        backBtnAH = new javax.swing.JLabel();
        txtAgregarImgHeroe = new javax.swing.JLabel();
        btnAgregarImgHeroe = new JLabel(new ImageIcon(image));
        txtAgregarImgAtaqueH = new javax.swing.JLabel();
        btnAgregarImgAtaqueH = new JLabel(new ImageIcon(image));
        sombraIdentidadSecretaH = new javax.swing.JPanel();
        txtIdentidadHeroe = new javax.swing.JLabel();
        idSecretaHeroe = new javax.swing.JTextField();
        sombraNombreHeroe = new javax.swing.JPanel();
        txtNombreHeroe = new javax.swing.JLabel();
        nombreHeroe = new javax.swing.JTextField();
        sombraArchienemigoH = new javax.swing.JPanel();
        txtArchienemigoH = new javax.swing.JLabel();
        comboboxArchienemigoH = new javax.swing.JComboBox<>();
        imgAtqHeroe = new javax.swing.JLabel();
        fondoAtqHeroe = new JLabel(new ImageIcon(mostrarPersonaje));
        sombraSeleccionarHeroeXML = new javax.swing.JPanel();
        txtSeleccionarHeroeXML = new javax.swing.JLabel();
        comboboxSelecHeroeXML = new javax.swing.JComboBox<>();
        txtCrearHeroe = new javax.swing.JLabel();
        btnCrearHeroe = new JLabel(new ImageIcon(image));
        imgHeroe = new javax.swing.JLabel();
        fondoDefHeroe = new javax.swing.JLabel();
        bannerHeroe = new javax.swing.JPanel();
        txtDatosHeroe = new javax.swing.JLabel();
        fondoAgregarHeroe = new javax.swing.JLabel();
        fondoAgregarHeroe1 = new javax.swing.JLabel();
        agregarAntiheroe = new javax.swing.JPanel();
        backBtnAAH = new javax.swing.JLabel();
        txtAgregarImgAtaqueAH = new javax.swing.JLabel();
        btnAgregarImgAtaqueAH = new JLabel(new ImageIcon(image));
        txtAgregarImgAntiheroe = new javax.swing.JLabel();
        btnAgregarImgAntiheroe = new JLabel(new ImageIcon(image));
        bannerAntiheroe = new javax.swing.JPanel();
        txtDatosHeroe1 = new javax.swing.JLabel();
        sombraIdentidadSecretaAH = new javax.swing.JPanel();
        txtIdentidadAntiheroe = new javax.swing.JLabel();
        idSecretaAntiheroe = new javax.swing.JTextField();
        sombraNombreAntiheroe = new javax.swing.JPanel();
        txtNombreAtiheroe = new javax.swing.JLabel();
        nombreAntiheroe = new javax.swing.JTextField();
        sombraArchienemigoAH = new javax.swing.JPanel();
        txtArchienemigoAH = new javax.swing.JLabel();
        comboboxArchienemigoAH = new javax.swing.JComboBox<>();
        imgAtqAntiheroe = new javax.swing.JLabel();
        fondoAtqAntiheroe = new JLabel(new ImageIcon(mostrarPersonaje));
        imgAntiheroe = new javax.swing.JLabel();
        fondoDefAntiheroe = new javax.swing.JLabel();
        sombraSeleccionarAntiheroeXML = new javax.swing.JPanel();
        txtSeleccionarHeroeXML1 = new javax.swing.JLabel();
        comboboxSelecAntiheroeXML = new javax.swing.JComboBox<>();
        txtCrearAntiheroe = new javax.swing.JLabel();
        btnCrearAntiheroe = new JLabel(new ImageIcon(image));
        fondoAgregarAntiheroe = new javax.swing.JLabel();
        agregarVillano = new javax.swing.JPanel();
        backBtnAV = new javax.swing.JLabel();
        txtAgregarImgVillano = new javax.swing.JLabel();
        btnAgregarImgVillano = new JLabel(new ImageIcon(image));
        txtAgregarImgAtaqueV = new javax.swing.JLabel();
        btnAgregarImgAtaqueV = new JLabel(new ImageIcon(image));
        bannerVillano = new javax.swing.JPanel();
        txtDatosVillano = new javax.swing.JLabel();
        sombraIdentidadSecretaV = new javax.swing.JPanel();
        txtIdentidadVillano = new javax.swing.JLabel();
        idSecretaVillano = new javax.swing.JTextField();
        sombraNombreVillano = new javax.swing.JPanel();
        txtNombreVillano = new javax.swing.JLabel();
        nombreVillano = new javax.swing.JTextField();
        sombraArchienemigoV = new javax.swing.JPanel();
        txtTipoVillano = new javax.swing.JLabel();
        comboboxTipoVillano = new javax.swing.JComboBox<>();
        imgAtqVillano = new javax.swing.JLabel();
        fondoAtqVillano = new JLabel(new ImageIcon(mostrarPersonaje));
        imgVillano = new javax.swing.JLabel();
        fondoDefVillano = new JLabel(new ImageIcon(mostrarPersonaje));
        sombraSeleccionarVillanoXML = new javax.swing.JPanel();
        txtSeleccionarHeroeXML2 = new javax.swing.JLabel();
        comboboxSelecVillanoXML = new javax.swing.JComboBox<>();
        txtCrearVillano = new javax.swing.JLabel();
        btnCrearVillano = new JLabel(new ImageIcon(image));
        fondoAgregarVillano = new javax.swing.JLabel();
        seleccionarCiudad = new javax.swing.JPanel();
        backBtnSC = new javax.swing.JLabel();
        txtSeleccionarMapa = new javax.swing.JLabel();
        btnSeleccionarPersonaje = new JLabel(new ImageIcon(image));
        scrollPanel = new javax.swing.JScrollPane();
        listaCiudades = new javax.swing.JList<>();
        previewImage = new javax.swing.JLabel();
        fondoSeleccionarCiudad = new javax.swing.JLabel();
        gestionCiudad = new javax.swing.JPanel();
        backBtnGC = new javax.swing.JLabel();
        txtCargarCiudad = new javax.swing.JLabel();
        btnCargarCiudad = new JLabel(new ImageIcon(image));
        txtEditarCiudad = new javax.swing.JLabel();
        txtAgregarCiudad = new javax.swing.JLabel();
        btnNuevaCiudad = new JLabel(new ImageIcon(image));
        btnEditarCiudad = new JLabel(new ImageIcon(image));
        fondoGestionCiudad = new javax.swing.JLabel();
        editarCiudad = new javax.swing.JPanel();
        backBtnGC1 = new javax.swing.JLabel();
        txtCargarCiudad1 = new javax.swing.JLabel();
        btnCargarCiudad1 = new JLabel(new ImageIcon(image));
        txtEditarCiudad1 = new javax.swing.JLabel();
        txtAgregarCiudad1 = new javax.swing.JLabel();
        btnAgregarVillano2 = new JLabel(new ImageIcon(image));
        btnAgregarAntiheroe2 = new JLabel(new ImageIcon(image));
        fondoGestionCiudad1 = new javax.swing.JLabel();
        agregarNuevaCiudad = new javax.swing.JPanel();
        backBtnAC = new javax.swing.JLabel();
        txtNombreCiudad = new javax.swing.JLabel();
        txtCrearCiudad = new javax.swing.JLabel();
        btnCrearCiudad = new JLabel(new ImageIcon(image));
        nombreCiudad = new javax.swing.JTextField();
        txtCargarImgCiudad = new javax.swing.JLabel();
        btnImagenCiudad = new JLabel(new ImageIcon(image));
        fondoGestionCiudad2 = new javax.swing.JLabel();
        batalla = new javax.swing.JPanel();
        backBtnB = new javax.swing.JLabel();
        imgHeroeAntiheroe = new javax.swing.JLabel();
        imgBatallaVillano = new javax.swing.JLabel();
        imgAtaqueVillano = new javax.swing.JLabel();
        imgAtaqueVillano.setVisible(false);
        imgAtqHeroeAntiheroe = new javax.swing.JLabel();
        imgAtqHeroeAntiheroe.setVisible(false);
        imgFight = new javax.swing.JLabel();
        btnFight = new JLabel(new ImageIcon(image));
        rondas = new javax.swing.JLabel();
        txtRondasGanadasVillano = new javax.swing.JLabel();
        rondasGanadasVillano = new javax.swing.JLabel();
        txtRondasGanadasHeroeAntiheroe = new javax.swing.JLabel();
        rondasGanadasHeroe = new javax.swing.JLabel();
        barraProbabilidad = new javax.swing.JProgressBar();
        escenarioBg = new javax.swing.JLabel();
        consultas = new javax.swing.JPanel();
        barraBusqueda = new javax.swing.JTextField();
        txtHeroes = new javax.swing.JLabel();
        txtVillanos = new javax.swing.JLabel();
        txtEfectividad = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar1 = new javax.swing.JProgressBar();
        btnBuscar = new javax.swing.JButton();
        panelPestañas = new javax.swing.JTabbedPane();
        pestañaEventos = new javax.swing.JScrollPane();
        tablaEventos = new javax.swing.JTable();
        pestañaEfectividad = new javax.swing.JScrollPane();
        listaCiudadesConsulta = new javax.swing.JList<>();
        backBtnC = new javax.swing.JLabel();
        bannerConsultas = new javax.swing.JPanel();
        txtMenuPrincipal1 = new javax.swing.JLabel();
        fondoConsultas = new javax.swing.JLabel();
        seleccionarPersonaje = new javax.swing.JPanel();
        backBtnSP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaVillanos = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaHeroesAntiheroes = new javax.swing.JList<>();
        txtEmpezarBatalla = new javax.swing.JLabel();
        btnEmpezarBatalla = new JLabel(new ImageIcon(image));
        fondoSeleccionarPersonaje = new javax.swing.JLabel();

        seleccionarArchivoXML.setApproveButtonText("Seleccionar");
        seleccionarArchivoXML.setCurrentDirectory(null);
        seleccionarArchivoXML.setFileFilter(new FileNameExtensionFilter("xml files (*.xml)", "xml"));

        seleccionarImagen.setCurrentDirectory(null);
        seleccionarImagen.setDialogTitle("");
        seleccionarImagen.setFileFilter(new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes()));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        menuPrincipal.setName("menuPrincipal"); // NOI18N
        menuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        banner.setBackground(new Color(0,0,0,75));

        txtMenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        txtMenuPrincipal.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        txtMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        txtMenuPrincipal.setText("Menu Principal");

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(txtMenuPrincipal)
                .addContainerGap(1220, Short.MAX_VALUE))
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addComponent(txtMenuPrincipal)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        menuPrincipal.add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1920, 60));

        txtJugar.setBackground(new java.awt.Color(255, 255, 255));
        txtJugar.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtJugar.setForeground(new java.awt.Color(255, 255, 255));
        txtJugar.setText("Jugar");
        menuPrincipal.add(txtJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 490, -1, -1));

        btnJugar.setForeground(new java.awt.Color(255, 255, 255));
        btnJugar.setBorder(null);
        btnJugar.setName("btn"); // NOI18N
        add(btnJugar);
        menuPrincipal.add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 460, 100));

        txtAgregarPersonajes.setBackground(new java.awt.Color(255, 255, 255));
        txtAgregarPersonajes.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtAgregarPersonajes.setForeground(new java.awt.Color(255, 255, 255));
        txtAgregarPersonajes.setText("Agregar Personajes");
        menuPrincipal.add(txtAgregarPersonajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 620, -1, -1));

        btnAgregarPersonaje.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarPersonaje.setBorder(null);
        btnAgregarPersonaje.setName("btn"); // NOI18N
        add(btnAgregarPersonaje);
        menuPrincipal.add(btnAgregarPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, 460, 100));

        txtGestionCiudad.setBackground(new java.awt.Color(255, 255, 255));
        txtGestionCiudad.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtGestionCiudad.setForeground(new java.awt.Color(255, 255, 255));
        txtGestionCiudad.setText("Gestion de Ciudad");
        menuPrincipal.add(txtGestionCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 750, -1, -1));

        btnGestionCiudad.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionCiudad.setBorder(null);
        btnGestionCiudad.setName("btn"); // NOI18N
        add(btnGestionCiudad);
        menuPrincipal.add(btnGestionCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 720, 460, 100));

        txtConsultas.setBackground(new java.awt.Color(255, 255, 255));
        txtConsultas.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtConsultas.setForeground(new java.awt.Color(255, 255, 255));
        txtConsultas.setText("Consultas");
        menuPrincipal.add(txtConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 870, -1, -1));

        btnConsultas.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultas.setBorder(null);
        btnConsultas.setName("btn"); // NOI18N
        add(btnConsultas);
        menuPrincipal.add(btnConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 850, 460, 100));

        exitButton.setIcon(    new ImageIcon(getImagePath("ExitButton",".png")));
        exitButton.setName("backBtn"); // NOI18N
        menuPrincipal.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 48, 48));
        exitButton.getAccessibleContext().setAccessibleParent(menuPrincipal);

        fondo.setIcon(new ImageIcon(getImagePath("MenuPrincipal",".jpg")));
        menuPrincipal.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        getContentPane().add(menuPrincipal);
        menuPrincipal.setBounds(0, 0, 1920, 1080);
        menuPrincipal.getAccessibleContext().setAccessibleName("menuPrincipal");

        agregarPersonaje.setName("agregarPersonaje"); // NOI18N
        agregarPersonaje.setPreferredSize(new java.awt.Dimension(1920, 1080));
        agregarPersonaje.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtnAP.setIcon(new ImageIcon(getImagePath("BackButton",".png")));
        backBtnAP.setName("backBtn"); // NOI18N
        agregarPersonaje.add(backBtnAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 48, 48));
        backBtnAP.getAccessibleContext().setAccessibleName("back");
        backBtnAP.getAccessibleContext().setAccessibleParent(menuPrincipal);

        txtAgregarHeroe.setBackground(new java.awt.Color(255, 255, 255));
        txtAgregarHeroe.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtAgregarHeroe.setForeground(new java.awt.Color(255, 255, 255));
        txtAgregarHeroe.setText("Agregar Héroe");
        agregarPersonaje.add(txtAgregarHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 540, -1, -1));

        btnAgregarHeroe.setName("btn"); // NOI18N
        agregarPersonaje.add(btnAgregarHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 460, 100));
        btnAgregarHeroe.getAccessibleContext().setAccessibleParent(menuPrincipal);

        txtAgregarAntiheroe.setBackground(new java.awt.Color(255, 255, 255));
        txtAgregarAntiheroe.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtAgregarAntiheroe.setForeground(new java.awt.Color(255, 255, 255));
        txtAgregarAntiheroe.setText("Agregar Antihéroe");
        agregarPersonaje.add(txtAgregarAntiheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 680, -1, -1));

        txtAgrergarVillano.setBackground(new java.awt.Color(255, 255, 255));
        txtAgrergarVillano.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtAgrergarVillano.setForeground(new java.awt.Color(255, 255, 255));
        txtAgrergarVillano.setText("Agregar Villano");
        agregarPersonaje.add(txtAgrergarVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 820, -1, -1));

        btnAgregarVillano.setName("btn"); // NOI18N
        agregarPersonaje.add(btnAgregarVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 800, 460, 100));

        btnAgregarAntiheroe.setName("btn"); // NOI18N
        agregarPersonaje.add(btnAgregarAntiheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 650, 460, 100));

        fondoAgregarPersonaje.setIcon(new ImageIcon(getImagePath("MenuPrincipal",".jpg")));
        agregarPersonaje.add(fondoAgregarPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));
        fondoAgregarPersonaje.getAccessibleContext().setAccessibleParent(menuPrincipal);

        getContentPane().add(agregarPersonaje);
        agregarPersonaje.setBounds(0, 0, 1920, 1080);
        agregarPersonaje.getAccessibleContext().setAccessibleParent(menuPrincipal);

        agregarHeroe.setName("agregarHeroe"); // NOI18N
        agregarHeroe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtnAH.setIcon(new ImageIcon(getImagePath("BackButton",".png")));
        backBtnAH.setName("backBtn"); // NOI18N
        agregarHeroe.add(backBtnAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 48, 48));
        backBtnAH.getAccessibleContext().setAccessibleParent(agregarPersonaje);

        txtAgregarImgHeroe.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtAgregarImgHeroe.setForeground(new java.awt.Color(255, 255, 255));
        txtAgregarImgHeroe.setText("Agregar imagen");
        txtAgregarImgHeroe.setAlignmentX(0.5F);
        agregarHeroe.add(txtAgregarImgHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 750, 290, 40));

        btnAgregarImgHeroe.setName("btn"); // NOI18N
        agregarHeroe.add(btnAgregarImgHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 720, 460, 100));

        txtAgregarImgAtaqueH.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtAgregarImgAtaqueH.setForeground(new java.awt.Color(255, 255, 255));
        txtAgregarImgAtaqueH.setText("Agregar imagen");
        txtAgregarImgAtaqueH.setAlignmentX(0.5F);
        agregarHeroe.add(txtAgregarImgAtaqueH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 750, 290, 40));

        btnAgregarImgAtaqueH.setName("btn"); // NOI18N
        agregarHeroe.add(btnAgregarImgAtaqueH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 720, 460, 100));

        sombraIdentidadSecretaH.setBackground(new Color(0,0,0,60));

        txtIdentidadHeroe.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtIdentidadHeroe.setForeground(new java.awt.Color(255, 255, 255));
        txtIdentidadHeroe.setText("Identidad secreta");

        javax.swing.GroupLayout sombraIdentidadSecretaHLayout = new javax.swing.GroupLayout(sombraIdentidadSecretaH);
        sombraIdentidadSecretaH.setLayout(sombraIdentidadSecretaHLayout);
        sombraIdentidadSecretaHLayout.setHorizontalGroup(
            sombraIdentidadSecretaHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sombraIdentidadSecretaHLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(txtIdentidadHeroe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sombraIdentidadSecretaHLayout.setVerticalGroup(
            sombraIdentidadSecretaHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sombraIdentidadSecretaHLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtIdentidadHeroe))
        );

        agregarHeroe.add(sombraIdentidadSecretaH, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 330, -1));
        agregarHeroe.add(idSecretaHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 400, 40));

        sombraNombreHeroe.setBackground(new Color(0,0,0,60));

        txtNombreHeroe.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtNombreHeroe.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreHeroe.setText("Nombre de héroe");

        javax.swing.GroupLayout sombraNombreHeroeLayout = new javax.swing.GroupLayout(sombraNombreHeroe);
        sombraNombreHeroe.setLayout(sombraNombreHeroeLayout);
        sombraNombreHeroeLayout.setHorizontalGroup(
            sombraNombreHeroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sombraNombreHeroeLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtNombreHeroe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sombraNombreHeroeLayout.setVerticalGroup(
            sombraNombreHeroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sombraNombreHeroeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtNombreHeroe))
        );

        agregarHeroe.add(sombraNombreHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 375, 320, -1));
        agregarHeroe.add(nombreHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 400, 40));

        sombraArchienemigoH.setBackground(new Color(0,0,0,60));

        txtArchienemigoH.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtArchienemigoH.setForeground(new java.awt.Color(255, 255, 255));
        txtArchienemigoH.setText("Archienemigo");

        javax.swing.GroupLayout sombraArchienemigoHLayout = new javax.swing.GroupLayout(sombraArchienemigoH);
        sombraArchienemigoH.setLayout(sombraArchienemigoHLayout);
        sombraArchienemigoHLayout.setHorizontalGroup(
            sombraArchienemigoHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sombraArchienemigoHLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(txtArchienemigoH)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sombraArchienemigoHLayout.setVerticalGroup(
            sombraArchienemigoHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sombraArchienemigoHLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtArchienemigoH))
        );

        agregarHeroe.add(sombraArchienemigoH, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 280, -1));

        agregarHeroe.add(comboboxArchienemigoH, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 600, 400, 40));

        imgAtqHeroe.setForeground(new java.awt.Color(255, 255, 255));
        agregarHeroe.add(imgAtqHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 180, 580, 508));

        fondoAtqHeroe.setForeground(new java.awt.Color(255, 255, 255));
        fondoAtqHeroe.setIcon(new ImageIcon(resizeImage(getImagePath("MarcoPersonaje",".png"),540,450)));
        fondoAtqHeroe.setBorder(null);
        fondoAtqHeroe.setName(""); // NOI18N
        add(fondoAtqHeroe);
        agregarHeroe.add(fondoAtqHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 220, 560, 400));

        sombraSeleccionarHeroeXML.setBackground(new Color(0,0,0,60));

        txtSeleccionarHeroeXML.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtSeleccionarHeroeXML.setForeground(new java.awt.Color(255, 255, 255));
        txtSeleccionarHeroeXML.setText("Seleccionar XML");

        javax.swing.GroupLayout sombraSeleccionarHeroeXMLLayout = new javax.swing.GroupLayout(sombraSeleccionarHeroeXML);
        sombraSeleccionarHeroeXML.setLayout(sombraSeleccionarHeroeXMLLayout);
        sombraSeleccionarHeroeXMLLayout.setHorizontalGroup(
            sombraSeleccionarHeroeXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sombraSeleccionarHeroeXMLLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(txtSeleccionarHeroeXML)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sombraSeleccionarHeroeXMLLayout.setVerticalGroup(
            sombraSeleccionarHeroeXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sombraSeleccionarHeroeXMLLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSeleccionarHeroeXML))
        );

        agregarHeroe.add(sombraSeleccionarHeroeXML, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 680, 320, -1));

        comboboxSelecHeroeXML.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XML" }));
        agregarHeroe.add(comboboxSelecHeroeXML, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 750, 400, 40));

        txtCrearHeroe.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtCrearHeroe.setForeground(new java.awt.Color(255, 255, 255));
        txtCrearHeroe.setText("Agregar Héroe");
        txtCrearHeroe.setAlignmentX(0.5F);
        agregarHeroe.add(txtCrearHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 920, 250, 40));

        btnCrearHeroe.setName("btn"); // NOI18N
        agregarHeroe.add(btnCrearHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 890, 460, 100));

        imgHeroe.setBackground(new java.awt.Color(0, 0, 0));
        imgHeroe.setForeground(new java.awt.Color(255, 255, 255));
        agregarHeroe.add(imgHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, 508));

        fondoDefHeroe.setForeground(new java.awt.Color(255, 255, 255));
        fondoDefHeroe.setIcon(new ImageIcon(resizeImage(getImagePath("MarcoPersonaje",".png"),540,450)));
        fondoDefHeroe.setBorder(null);
        fondoDefHeroe.setName(""); // NOI18N
        agregarHeroe.add(fondoDefHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        bannerHeroe.setBackground(new Color(0,0,0,75));

        txtDatosHeroe.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        txtDatosHeroe.setForeground(new java.awt.Color(255, 255, 255));
        txtDatosHeroe.setText("Datos del héroe");

        javax.swing.GroupLayout bannerHeroeLayout = new javax.swing.GroupLayout(bannerHeroe);
        bannerHeroe.setLayout(bannerHeroeLayout);
        bannerHeroeLayout.setHorizontalGroup(
            bannerHeroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerHeroeLayout.createSequentialGroup()
                .addGap(0, 400, Short.MAX_VALUE)
                .addComponent(txtDatosHeroe)
                .addGap(0, 156, Short.MAX_VALUE))
        );
        bannerHeroeLayout.setVerticalGroup(
            bannerHeroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerHeroeLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(txtDatosHeroe)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        agregarHeroe.add(bannerHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 920, 60));

        fondoAgregarHeroe.setIcon(new ImageIcon(getImagePath("MenuPrincipal",".jpg")));
        agregarHeroe.add(fondoAgregarHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        fondoAgregarHeroe1.setIcon(new ImageIcon(getImagePath("MenuPrincipal",".jpg")));
        agregarHeroe.add(fondoAgregarHeroe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1920, 1080));

        getContentPane().add(agregarHeroe);
        agregarHeroe.setBounds(0, 0, 1920, 1230);
        agregarHeroe.getAccessibleContext().setAccessibleParent(agregarPersonaje);

        agregarAntiheroe.setName("agregarAntiheroe"); // NOI18N
        agregarAntiheroe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtnAAH.setIcon(new ImageIcon(getImagePath("BackButton",".png")));
        backBtnAAH.setName("backBtn"); // NOI18N
        agregarAntiheroe.add(backBtnAAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 48, 48));
        backBtnAAH.getAccessibleContext().setAccessibleParent(agregarPersonaje);

        txtAgregarImgAtaqueAH.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtAgregarImgAtaqueAH.setForeground(new java.awt.Color(255, 255, 255));
        txtAgregarImgAtaqueAH.setText("Agregar imagen");
        txtAgregarImgAtaqueAH.setAlignmentX(0.5F);
        agregarAntiheroe.add(txtAgregarImgAtaqueAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 750, 290, 40));

        btnAgregarImgAtaqueAH.setName("btn"); // NOI18N
        agregarAntiheroe.add(btnAgregarImgAtaqueAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 720, 460, 100));

        txtAgregarImgAntiheroe.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtAgregarImgAntiheroe.setForeground(new java.awt.Color(255, 255, 255));
        txtAgregarImgAntiheroe.setText("Agregar imagen");
        txtAgregarImgAntiheroe.setAlignmentX(0.5F);
        agregarAntiheroe.add(txtAgregarImgAntiheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 750, 290, 40));

        btnAgregarImgAntiheroe.setName("btn"); // NOI18N
        agregarAntiheroe.add(btnAgregarImgAntiheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 720, 460, 100));

        bannerAntiheroe.setBackground(new Color(0,0,0,75));

        txtDatosHeroe1.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        txtDatosHeroe1.setForeground(new java.awt.Color(255, 255, 255));
        txtDatosHeroe1.setText("Datos del antihéroe");

        javax.swing.GroupLayout bannerAntiheroeLayout = new javax.swing.GroupLayout(bannerAntiheroe);
        bannerAntiheroe.setLayout(bannerAntiheroeLayout);
        bannerAntiheroeLayout.setHorizontalGroup(
            bannerAntiheroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerAntiheroeLayout.createSequentialGroup()
                .addGap(0, 355, Short.MAX_VALUE)
                .addComponent(txtDatosHeroe1)
                .addGap(0, 111, Short.MAX_VALUE))
        );
        bannerAntiheroeLayout.setVerticalGroup(
            bannerAntiheroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerAntiheroeLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(txtDatosHeroe1)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        agregarAntiheroe.add(bannerAntiheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 920, 60));

        sombraIdentidadSecretaAH.setBackground(new Color(0,0,0,60));

        txtIdentidadAntiheroe.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtIdentidadAntiheroe.setForeground(new java.awt.Color(255, 255, 255));
        txtIdentidadAntiheroe.setText("Identidad secreta");

        javax.swing.GroupLayout sombraIdentidadSecretaAHLayout = new javax.swing.GroupLayout(sombraIdentidadSecretaAH);
        sombraIdentidadSecretaAH.setLayout(sombraIdentidadSecretaAHLayout);
        sombraIdentidadSecretaAHLayout.setHorizontalGroup(
            sombraIdentidadSecretaAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sombraIdentidadSecretaAHLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(txtIdentidadAntiheroe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sombraIdentidadSecretaAHLayout.setVerticalGroup(
            sombraIdentidadSecretaAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sombraIdentidadSecretaAHLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtIdentidadAntiheroe))
        );

        agregarAntiheroe.add(sombraIdentidadSecretaAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 330, -1));
        agregarAntiheroe.add(idSecretaAntiheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 400, 40));

        sombraNombreAntiheroe.setBackground(new Color(0,0,0,60));

        txtNombreAtiheroe.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtNombreAtiheroe.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreAtiheroe.setText("Nombre de antihéroe");

        javax.swing.GroupLayout sombraNombreAntiheroeLayout = new javax.swing.GroupLayout(sombraNombreAntiheroe);
        sombraNombreAntiheroe.setLayout(sombraNombreAntiheroeLayout);
        sombraNombreAntiheroeLayout.setHorizontalGroup(
            sombraNombreAntiheroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sombraNombreAntiheroeLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtNombreAtiheroe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sombraNombreAntiheroeLayout.setVerticalGroup(
            sombraNombreAntiheroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sombraNombreAntiheroeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtNombreAtiheroe))
        );

        agregarAntiheroe.add(sombraNombreAntiheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 375, 385, -1));
        agregarAntiheroe.add(nombreAntiheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 400, 40));

        sombraArchienemigoAH.setBackground(new Color(0,0,0,60));

        txtArchienemigoAH.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtArchienemigoAH.setForeground(new java.awt.Color(255, 255, 255));
        txtArchienemigoAH.setText("Archienemigo");

        javax.swing.GroupLayout sombraArchienemigoAHLayout = new javax.swing.GroupLayout(sombraArchienemigoAH);
        sombraArchienemigoAH.setLayout(sombraArchienemigoAHLayout);
        sombraArchienemigoAHLayout.setHorizontalGroup(
            sombraArchienemigoAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sombraArchienemigoAHLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(txtArchienemigoAH)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sombraArchienemigoAHLayout.setVerticalGroup(
            sombraArchienemigoAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sombraArchienemigoAHLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtArchienemigoAH))
        );

        agregarAntiheroe.add(sombraArchienemigoAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 280, -1));

        agregarAntiheroe.add(comboboxArchienemigoAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 600, 400, 40));

        imgAtqAntiheroe.setForeground(new java.awt.Color(255, 255, 255));
        imgAtqAntiheroe.setIcon(new ImageIcon(getSpritePath("default",".png")));
        agregarAntiheroe.add(imgAtqAntiheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 180, 580, 508));

        fondoAtqAntiheroe.setForeground(new java.awt.Color(255, 255, 255));
        fondoAtqAntiheroe.setIcon(new ImageIcon(resizeImage(getImagePath("MarcoPersonaje",".png"),540,450)));
        fondoAtqAntiheroe.setBorder(null);
        fondoAtqAntiheroe.setName(""); // NOI18N
        add(fondoAtqAntiheroe);
        agregarAntiheroe.add(fondoAtqAntiheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 220, 560, 400));

        imgAntiheroe.setBackground(new java.awt.Color(0, 0, 0));
        imgAntiheroe.setForeground(new java.awt.Color(255, 255, 255));
        imgAntiheroe.setIcon(new ImageIcon(getSpritePath("default1",".png")));
        agregarAntiheroe.add(imgAntiheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, 508));

        fondoDefAntiheroe.setForeground(new java.awt.Color(255, 255, 255));
        fondoDefAntiheroe.setIcon(new ImageIcon(resizeImage(getImagePath("MarcoPersonaje",".png"),540,450)));
        fondoDefAntiheroe.setBorder(null);
        fondoDefAntiheroe.setName(""); // NOI18N
        agregarAntiheroe.add(fondoDefAntiheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 560, 400));

        sombraSeleccionarAntiheroeXML.setBackground(new Color(0,0,0,60));

        txtSeleccionarHeroeXML1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtSeleccionarHeroeXML1.setForeground(new java.awt.Color(255, 255, 255));
        txtSeleccionarHeroeXML1.setText("Seleccionar XML");

        javax.swing.GroupLayout sombraSeleccionarAntiheroeXMLLayout = new javax.swing.GroupLayout(sombraSeleccionarAntiheroeXML);
        sombraSeleccionarAntiheroeXML.setLayout(sombraSeleccionarAntiheroeXMLLayout);
        sombraSeleccionarAntiheroeXMLLayout.setHorizontalGroup(
            sombraSeleccionarAntiheroeXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sombraSeleccionarAntiheroeXMLLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(txtSeleccionarHeroeXML1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sombraSeleccionarAntiheroeXMLLayout.setVerticalGroup(
            sombraSeleccionarAntiheroeXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sombraSeleccionarAntiheroeXMLLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSeleccionarHeroeXML1))
        );

        agregarAntiheroe.add(sombraSeleccionarAntiheroeXML, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 680, 320, -1));

        comboboxSelecAntiheroeXML.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XML" }));
        agregarAntiheroe.add(comboboxSelecAntiheroeXML, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 750, 400, 40));

        txtCrearAntiheroe.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtCrearAntiheroe.setForeground(new java.awt.Color(255, 255, 255));
        txtCrearAntiheroe.setText("Agregar Antihéroe");
        txtCrearAntiheroe.setAlignmentX(0.5F);
        agregarAntiheroe.add(txtCrearAntiheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 920, 310, 40));

        btnCrearAntiheroe.setName("btn"); // NOI18N
        agregarAntiheroe.add(btnCrearAntiheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 890, 460, 100));

        fondoAgregarAntiheroe.setIcon(new ImageIcon(getImagePath("MenuPrincipal",".jpg")));
        agregarAntiheroe.add(fondoAgregarAntiheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        getContentPane().add(agregarAntiheroe);
        agregarAntiheroe.setBounds(0, 0, 1920, 1080);

        agregarVillano.setName("agregarVillano"); // NOI18N
        agregarVillano.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtnAV.setIcon(new ImageIcon(getImagePath("BackButton",".png")));
        backBtnAV.setName("backBtn"); // NOI18N
        agregarVillano.add(backBtnAV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 48, 48));
        backBtnAV.getAccessibleContext().setAccessibleParent(agregarPersonaje);

        txtAgregarImgVillano.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtAgregarImgVillano.setForeground(new java.awt.Color(255, 255, 255));
        txtAgregarImgVillano.setText("Agregar imagen");
        txtAgregarImgVillano.setAlignmentX(0.5F);
        agregarVillano.add(txtAgregarImgVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 750, 290, 40));

        btnAgregarImgVillano.setName("btn"); // NOI18N
        agregarVillano.add(btnAgregarImgVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 720, 460, 100));

        txtAgregarImgAtaqueV.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtAgregarImgAtaqueV.setForeground(new java.awt.Color(255, 255, 255));
        txtAgregarImgAtaqueV.setText("Agregar imagen");
        txtAgregarImgAtaqueV.setAlignmentX(0.5F);
        agregarVillano.add(txtAgregarImgAtaqueV, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 750, 290, 40));

        btnAgregarImgAtaqueV.setName("btn"); // NOI18N
        agregarVillano.add(btnAgregarImgAtaqueV, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 720, 460, 100));

        bannerVillano.setBackground(new Color(0,0,0,75));

        txtDatosVillano.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        txtDatosVillano.setForeground(new java.awt.Color(255, 255, 255));
        txtDatosVillano.setText("Datos del villano");

        javax.swing.GroupLayout bannerVillanoLayout = new javax.swing.GroupLayout(bannerVillano);
        bannerVillano.setLayout(bannerVillanoLayout);
        bannerVillanoLayout.setHorizontalGroup(
            bannerVillanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerVillanoLayout.createSequentialGroup()
                .addGap(0, 389, Short.MAX_VALUE)
                .addComponent(txtDatosVillano)
                .addGap(0, 146, Short.MAX_VALUE))
        );
        bannerVillanoLayout.setVerticalGroup(
            bannerVillanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerVillanoLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(txtDatosVillano)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        agregarVillano.add(bannerVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 920, 60));

        sombraIdentidadSecretaV.setBackground(new Color(0,0,0,60));

        txtIdentidadVillano.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtIdentidadVillano.setForeground(new java.awt.Color(255, 255, 255));
        txtIdentidadVillano.setText("Identidad secreta");

        javax.swing.GroupLayout sombraIdentidadSecretaVLayout = new javax.swing.GroupLayout(sombraIdentidadSecretaV);
        sombraIdentidadSecretaV.setLayout(sombraIdentidadSecretaVLayout);
        sombraIdentidadSecretaVLayout.setHorizontalGroup(
            sombraIdentidadSecretaVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sombraIdentidadSecretaVLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(txtIdentidadVillano)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sombraIdentidadSecretaVLayout.setVerticalGroup(
            sombraIdentidadSecretaVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sombraIdentidadSecretaVLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtIdentidadVillano))
        );

        agregarVillano.add(sombraIdentidadSecretaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 330, -1));
        agregarVillano.add(idSecretaVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 400, 40));

        sombraNombreVillano.setBackground(new Color(0,0,0,60));

        txtNombreVillano.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtNombreVillano.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreVillano.setText("Nombre de villano");

        javax.swing.GroupLayout sombraNombreVillanoLayout = new javax.swing.GroupLayout(sombraNombreVillano);
        sombraNombreVillano.setLayout(sombraNombreVillanoLayout);
        sombraNombreVillanoLayout.setHorizontalGroup(
            sombraNombreVillanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sombraNombreVillanoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtNombreVillano)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sombraNombreVillanoLayout.setVerticalGroup(
            sombraNombreVillanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sombraNombreVillanoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtNombreVillano))
        );

        agregarVillano.add(sombraNombreVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 375, 385, -1));
        agregarVillano.add(nombreVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 400, 40));

        sombraArchienemigoV.setBackground(new Color(0,0,0,60));

        txtTipoVillano.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtTipoVillano.setForeground(new java.awt.Color(255, 255, 255));
        txtTipoVillano.setText("Tipo de villano");

        javax.swing.GroupLayout sombraArchienemigoVLayout = new javax.swing.GroupLayout(sombraArchienemigoV);
        sombraArchienemigoV.setLayout(sombraArchienemigoVLayout);
        sombraArchienemigoVLayout.setHorizontalGroup(
            sombraArchienemigoVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sombraArchienemigoVLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(txtTipoVillano)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sombraArchienemigoVLayout.setVerticalGroup(
            sombraArchienemigoVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sombraArchienemigoVLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtTipoVillano))
        );

        agregarVillano.add(sombraArchienemigoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 280, -1));

        comboboxTipoVillano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Social", "Economico" }));
        agregarVillano.add(comboboxTipoVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 600, 400, 40));

        imgAtqVillano.setForeground(new java.awt.Color(255, 255, 255));
        imgAtqVillano.setIcon(new ImageIcon(getSpritePath("default",".png")));
        agregarVillano.add(imgAtqVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 180, 580, 508));

        fondoAtqVillano.setForeground(new java.awt.Color(255, 255, 255));
        fondoAtqVillano.setIcon(new ImageIcon(resizeImage(getImagePath("MarcoPersonaje",".png"),540,450)));
        fondoAtqVillano.setBorder(null);
        fondoAtqVillano.setName(""); // NOI18N
        add(fondoAtqVillano);
        agregarVillano.add(fondoAtqVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 220, 560, 400));

        imgVillano.setBackground(new java.awt.Color(0, 0, 0));
        imgVillano.setForeground(new java.awt.Color(255, 255, 255));
        imgVillano.setIcon(new ImageIcon(getSpritePath("default1",".png")));
        agregarVillano.add(imgVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, 508));

        fondoDefVillano.setForeground(new java.awt.Color(255, 255, 255));
        fondoDefVillano.setIcon(new ImageIcon(resizeImage(getImagePath("MarcoPersonaje",".png"),540,450)));
        fondoDefVillano.setBorder(null);
        fondoDefVillano.setName(""); // NOI18N
        add(fondoDefVillano);
        agregarVillano.add(fondoDefVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 560, 400));

        sombraSeleccionarVillanoXML.setBackground(new Color(0,0,0,60));

        txtSeleccionarHeroeXML2.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtSeleccionarHeroeXML2.setForeground(new java.awt.Color(255, 255, 255));
        txtSeleccionarHeroeXML2.setText("Seleccionar XML");

        javax.swing.GroupLayout sombraSeleccionarVillanoXMLLayout = new javax.swing.GroupLayout(sombraSeleccionarVillanoXML);
        sombraSeleccionarVillanoXML.setLayout(sombraSeleccionarVillanoXMLLayout);
        sombraSeleccionarVillanoXMLLayout.setHorizontalGroup(
            sombraSeleccionarVillanoXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sombraSeleccionarVillanoXMLLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(txtSeleccionarHeroeXML2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sombraSeleccionarVillanoXMLLayout.setVerticalGroup(
            sombraSeleccionarVillanoXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sombraSeleccionarVillanoXMLLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSeleccionarHeroeXML2))
        );

        agregarVillano.add(sombraSeleccionarVillanoXML, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 680, 320, -1));

        comboboxSelecVillanoXML.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XML" }));
        agregarVillano.add(comboboxSelecVillanoXML, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 750, 400, 40));

        txtCrearVillano.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtCrearVillano.setForeground(new java.awt.Color(255, 255, 255));
        txtCrearVillano.setText("Agregar Villano");
        txtCrearVillano.setAlignmentX(0.5F);
        agregarVillano.add(txtCrearVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 920, 260, 40));

        btnCrearVillano.setName("btn"); // NOI18N
        agregarVillano.add(btnCrearVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 890, 460, 100));

        fondoAgregarVillano.setIcon(new ImageIcon(getImagePath("MenuPrincipal",".jpg")));
        agregarVillano.add(fondoAgregarVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        getContentPane().add(agregarVillano);
        agregarVillano.setBounds(0, 0, 1920, 1080);

        seleccionarCiudad.setName("seleccionarCiudad"); // NOI18N
        seleccionarCiudad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtnSC.setIcon(new ImageIcon(getImagePath("BackButton",".png")));
        backBtnSC.setName("backBtn"); // NOI18N
        seleccionarCiudad.add(backBtnSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 48, 48));
        backBtnSC.getAccessibleContext().setAccessibleParent(menuPrincipal);

        txtSeleccionarMapa.setBackground(new java.awt.Color(255, 255, 255));
        txtSeleccionarMapa.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtSeleccionarMapa.setForeground(new java.awt.Color(255, 255, 255));
        txtSeleccionarMapa.setText("Seleccionar Mapa");
        seleccionarCiudad.add(txtSeleccionarMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 920, -1, -1));

        btnSeleccionarPersonaje.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarPersonaje.setBorder(null);
        btnSeleccionarPersonaje.setName("btn"); // NOI18N
        add(btnSeleccionarPersonaje);
        seleccionarCiudad.add(btnSeleccionarPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 900, 460, 100));

        scrollPanel.setBackground(new Color(255,255,255,90));
        scrollPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        scrollPanel.setForeground(new Color(0,0,0,75));

        listaCiudades.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        listaCiudades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "mapa1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaCiudades.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPanel.setViewportView(listaCiudades);

        seleccionarCiudad.add(scrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 560, 660));
        seleccionarCiudad.add(previewImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 120, 640, 420));

        fondoSeleccionarCiudad.setIcon(new ImageIcon(getImagePath("SeleccionarCiudad",".jpg")));
        seleccionarCiudad.add(fondoSeleccionarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        getContentPane().add(seleccionarCiudad);
        seleccionarCiudad.setBounds(0, 0, 1920, 1080);
        seleccionarCiudad.getAccessibleContext().setAccessibleName("seleccionarCiudad");
        seleccionarCiudad.getAccessibleContext().setAccessibleParent(agregarPersonaje);

        gestionCiudad.setName("gestionCiudad"); // NOI18N
        gestionCiudad.setPreferredSize(new java.awt.Dimension(1290, 1080));
        gestionCiudad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtnGC.setIcon(new ImageIcon(getImagePath("BackButton",".png")));
        backBtnGC.setName("backBtn"); // NOI18N
        gestionCiudad.add(backBtnGC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 48, 48));
        backBtnGC.getAccessibleContext().setAccessibleParent(menuPrincipal);

        txtCargarCiudad.setBackground(new java.awt.Color(255, 255, 255));
        txtCargarCiudad.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtCargarCiudad.setForeground(new java.awt.Color(255, 255, 255));
        txtCargarCiudad.setText("Cargar ciudad");
        gestionCiudad.add(txtCargarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 540, -1, -1));

        btnCargarCiudad.setName("btn"); // NOI18N
        gestionCiudad.add(btnCargarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 460, 100));

        txtEditarCiudad.setBackground(new java.awt.Color(255, 255, 255));
        txtEditarCiudad.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtEditarCiudad.setForeground(new java.awt.Color(255, 255, 255));
        txtEditarCiudad.setText("Editar una ciudad");
        gestionCiudad.add(txtEditarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 680, -1, -1));

        txtAgregarCiudad.setBackground(new java.awt.Color(255, 255, 255));
        txtAgregarCiudad.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtAgregarCiudad.setForeground(new java.awt.Color(255, 255, 255));
        txtAgregarCiudad.setText("Agregar una nueva ciudad");
        gestionCiudad.add(txtAgregarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 830, -1, -1));

        btnNuevaCiudad.setName("btn"); // NOI18N
        gestionCiudad.add(btnNuevaCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 800, 460, 100));

        btnEditarCiudad.setName("btn"); // NOI18N
        gestionCiudad.add(btnEditarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 650, 460, 100));

        fondoGestionCiudad.setIcon(new ImageIcon(getImagePath("MenuPrincipal",".jpg")));
        gestionCiudad.add(fondoGestionCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        getContentPane().add(gestionCiudad);
        gestionCiudad.setBounds(0, 0, 1920, 1080);
        gestionCiudad.getAccessibleContext().setAccessibleName("");

        editarCiudad.setName("editarCiudad"); // NOI18N
        editarCiudad.setPreferredSize(new java.awt.Dimension(1290, 1080));
        editarCiudad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtnGC1.setIcon(new ImageIcon(getImagePath("BackButton",".png")));
        backBtnGC1.setName("backBtn"); // NOI18N
        editarCiudad.add(backBtnGC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 48, 48));

        txtCargarCiudad1.setBackground(new java.awt.Color(255, 255, 255));
        txtCargarCiudad1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtCargarCiudad1.setForeground(new java.awt.Color(255, 255, 255));
        txtCargarCiudad1.setText("Cargar ciudad");
        editarCiudad.add(txtCargarCiudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 540, -1, -1));

        btnCargarCiudad1.setName("btn"); // NOI18N
        editarCiudad.add(btnCargarCiudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 460, 100));

        txtEditarCiudad1.setBackground(new java.awt.Color(255, 255, 255));
        txtEditarCiudad1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtEditarCiudad1.setForeground(new java.awt.Color(255, 255, 255));
        txtEditarCiudad1.setText("Editar una ciudad");
        editarCiudad.add(txtEditarCiudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 680, -1, -1));

        txtAgregarCiudad1.setBackground(new java.awt.Color(255, 255, 255));
        txtAgregarCiudad1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtAgregarCiudad1.setForeground(new java.awt.Color(255, 255, 255));
        txtAgregarCiudad1.setText("Agregar una nueva ciudad");
        editarCiudad.add(txtAgregarCiudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 830, -1, -1));

        btnAgregarVillano2.setName("btn"); // NOI18N
        editarCiudad.add(btnAgregarVillano2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 800, 460, 100));

        btnAgregarAntiheroe2.setName("btn"); // NOI18N
        editarCiudad.add(btnAgregarAntiheroe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 650, 460, 100));

        fondoGestionCiudad1.setIcon(new ImageIcon(getImagePath("MenuPrincipal",".jpg")));
        editarCiudad.add(fondoGestionCiudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        getContentPane().add(editarCiudad);
        editarCiudad.setBounds(0, 0, 1920, 1080);

        agregarNuevaCiudad.setName("agregarNuevaCiudad"); // NOI18N
        agregarNuevaCiudad.setPreferredSize(new java.awt.Dimension(1290, 1080));
        agregarNuevaCiudad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtnAC.setIcon(new ImageIcon(getImagePath("BackButton",".png")));
        backBtnAC.setName("backBtn"); // NOI18N
        agregarNuevaCiudad.add(backBtnAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 48, 48));
        backBtnAC.getAccessibleContext().setAccessibleParent(gestionCiudad);

        txtNombreCiudad.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreCiudad.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtNombreCiudad.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreCiudad.setText("Nombre de la ciudad");
        agregarNuevaCiudad.add(txtNombreCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, -1, -1));

        txtCrearCiudad.setBackground(new java.awt.Color(255, 255, 255));
        txtCrearCiudad.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtCrearCiudad.setForeground(new java.awt.Color(255, 255, 255));
        txtCrearCiudad.setText("Agregar una nueva ciudad");
        agregarNuevaCiudad.add(txtCrearCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 830, -1, -1));

        btnCrearCiudad.setName("btn"); // NOI18N
        agregarNuevaCiudad.add(btnCrearCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 800, 460, 100));
        agregarNuevaCiudad.add(nombreCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 460, 60));

        txtCargarImgCiudad.setBackground(new java.awt.Color(255, 255, 255));
        txtCargarImgCiudad.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtCargarImgCiudad.setForeground(new java.awt.Color(255, 255, 255));
        txtCargarImgCiudad.setText("Cargar imagen ciudad");
        agregarNuevaCiudad.add(txtCargarImgCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 610, -1, -1));

        btnImagenCiudad.setName("btn"); // NOI18N
        agregarNuevaCiudad.add(btnImagenCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 580, 460, 100));

        fondoGestionCiudad2.setIcon(new ImageIcon(getImagePath("MenuPrincipal",".jpg")));
        agregarNuevaCiudad.add(fondoGestionCiudad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        getContentPane().add(agregarNuevaCiudad);
        agregarNuevaCiudad.setBounds(0, 0, 1920, 1080);

        batalla.setName("batalla"); // NOI18N
        batalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtnB.setIcon(new ImageIcon(getImagePath("BackButton",".png")));
        backBtnB.setName("backBtn"); // NOI18N
        batalla.add(backBtnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 48, 48));
        backBtnB.getAccessibleContext().setAccessibleParent(seleccionarCiudad);

        imgHeroeAntiheroe.setBorder(null);
        batalla.add(imgHeroeAntiheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 420, 360));

        imgBatallaVillano.setBorder(null);
        batalla.add(imgBatallaVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 410, 420, 360));

        imgAtaqueVillano.setBorder(null);
        batalla.add(imgAtaqueVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 90, 750, 410));

        imgAtqHeroeAntiheroe.setBorder(null);
        batalla.add(imgAtqHeroeAntiheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 750, 410));

        imgFight.setIcon(new ImageIcon(resizeImage(getImagePath("FightBtn",".png"),300,100)));
        batalla.add(imgFight, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 850, 460, 100));

        btnFight.setName("btn"); // NOI18N
        batalla.add(btnFight, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 850, 460, 100));

        rondas.setFont(rondas.getFont().deriveFont(rondas.getFont().getStyle() | java.awt.Font.BOLD, 121));
        rondas.setForeground(new java.awt.Color(255, 255, 255));
        rondas.setText("0");
        batalla.add(rondas, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 46, 180, 220));

        txtRondasGanadasVillano.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        txtRondasGanadasVillano.setForeground(new java.awt.Color(255, 255, 255));
        txtRondasGanadasVillano.setText("Rondas Ganadas: ");
        batalla.add(txtRondasGanadasVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 20, -1, -1));

        rondasGanadasVillano.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        rondasGanadasVillano.setForeground(new java.awt.Color(255, 255, 255));
        rondasGanadasVillano.setText("0");
        batalla.add(rondasGanadasVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 20, 70, 60));

        txtRondasGanadasHeroeAntiheroe.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        txtRondasGanadasHeroeAntiheroe.setForeground(new java.awt.Color(255, 255, 255));
        txtRondasGanadasHeroeAntiheroe.setText("Rondas Ganadas: ");
        batalla.add(txtRondasGanadasHeroeAntiheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        rondasGanadasHeroe.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        rondasGanadasHeroe.setForeground(new java.awt.Color(255, 255, 255));
        rondasGanadasHeroe.setText("0");
        batalla.add(rondasGanadasHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 70, 60));

        barraProbabilidad.setStringPainted(true);
        batalla.add(barraProbabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 670, 450, 30));

        escenarioBg.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        escenarioBg.setIcon(new ImageIcon(getImagePath("MenuPrincipal",".jpg")));
        batalla.add(escenarioBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        getContentPane().add(batalla);
        batalla.setBounds(0, 0, 1920, 1080);

        consultas.setName("consultas"); // NOI18N
        consultas.setPreferredSize(new java.awt.Dimension(1920, 1080));
        consultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        consultas.add(barraBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 380, 30));

        txtHeroes.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        txtHeroes.setForeground(new java.awt.Color(255, 255, 255));
        txtHeroes.setText("Heroes");
        consultas.add(txtHeroes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 125, -1, 20));
        txtHeroes.getAccessibleContext().setAccessibleName("");

        txtVillanos.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        txtVillanos.setForeground(new java.awt.Color(255, 255, 255));
        txtVillanos.setText("Villanos");
        consultas.add(txtVillanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 205, -1, 20));
        txtVillanos.getAccessibleContext().setAccessibleName("");

        txtEfectividad.setBackground(new java.awt.Color(255, 255, 255));
        txtEfectividad.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        txtEfectividad.setForeground(new java.awt.Color(255, 255, 255));
        txtEfectividad.setText("Efectividad");
        consultas.add(txtEfectividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 30, 150, 40));

        jProgressBar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jProgressBar2.setStringPainted(true);
        consultas.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 200, 400, 30));

        jProgressBar1.setToolTipText("");
        jProgressBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jProgressBar1.setStringPainted(true);
        consultas.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 120, 400, 30));

        btnBuscar.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setName("btn"); // NOI18N
        consultas.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, 30));

        panelPestañas.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N

        tablaEventos.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        tablaEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre del Personaje", "Eventos Ganados", "Eventos Perdidos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pestañaEventos.setViewportView(tablaEventos);

        panelPestañas.addTab("Eventos", pestañaEventos);

        listaCiudadesConsulta.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        pestañaEfectividad.setViewportView(listaCiudadesConsulta);
        listaCiudadesConsulta.getAccessibleContext().setAccessibleName("listaCiudades");

        panelPestañas.addTab("Efectividad", pestañaEfectividad);

        consultas.add(panelPestañas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 1790, 640));

        backBtnC.setIcon(new ImageIcon(getImagePath("BackButton",".png")));
        backBtnC.setName("backBtn"); // NOI18N
        consultas.add(backBtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 48, 48));
        backBtnC.getAccessibleContext().setAccessibleParent(menuPrincipal);

        bannerConsultas.setBackground(new Color(0,0,0,75));

        txtMenuPrincipal1.setBackground(new java.awt.Color(255, 255, 255));
        txtMenuPrincipal1.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        txtMenuPrincipal1.setForeground(new java.awt.Color(255, 255, 255));
        txtMenuPrincipal1.setText("Consultas");

        javax.swing.GroupLayout bannerConsultasLayout = new javax.swing.GroupLayout(bannerConsultas);
        bannerConsultas.setLayout(bannerConsultasLayout);
        bannerConsultasLayout.setHorizontalGroup(
            bannerConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerConsultasLayout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(txtMenuPrincipal1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bannerConsultasLayout.setVerticalGroup(
            bannerConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerConsultasLayout.createSequentialGroup()
                .addComponent(txtMenuPrincipal1)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        consultas.add(bannerConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 960, 60));

        fondoConsultas.setIcon(new ImageIcon(getImagePath("MenuPrincipal",".jpg")));
        consultas.add(fondoConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));
        fondoConsultas.getAccessibleContext().setAccessibleName("fondoConsultas");
        fondoConsultas.getAccessibleContext().setAccessibleParent(menuPrincipal);

        getContentPane().add(consultas);
        consultas.setBounds(0, 0, 1920, 1080);

        seleccionarPersonaje.setName("seleccionarPersonaje"); // NOI18N
        seleccionarPersonaje.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtnSP.setIcon(new ImageIcon(getImagePath("BackButton",".png")));
        backBtnSP.setName("backBtn"); // NOI18N
        seleccionarPersonaje.add(backBtnSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 48, 48));
        backBtnSP.getAccessibleContext().setAccessibleParent(seleccionarCiudad);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Villanos");
        seleccionarPersonaje.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 150, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Heroes/Antiheroes");
        seleccionarPersonaje.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        listaVillanos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listaVillanos);

        seleccionarPersonaje.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 250, 470, 570));

        listaHeroesAntiheroes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listaHeroesAntiheroes);

        seleccionarPersonaje.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 470, 570));

        txtEmpezarBatalla.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        txtEmpezarBatalla.setForeground(new java.awt.Color(255, 255, 255));
        txtEmpezarBatalla.setText("Empezar Batalla");
        txtEmpezarBatalla.setAlignmentX(0.5F);
        seleccionarPersonaje.add(txtEmpezarBatalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 940, 290, 40));

        btnEmpezarBatalla.setName("btn"); // NOI18N
        seleccionarPersonaje.add(btnEmpezarBatalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 910, 460, 100));

        fondoSeleccionarPersonaje.setIcon(new ImageIcon(getImagePath("SeleccionarCiudad",".jpg")));
        seleccionarPersonaje.add(fondoSeleccionarPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        getContentPane().add(seleccionarPersonaje);
        seleccionarPersonaje.setBounds(0, 0, 1920, 1080);

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private String getImagePath(String pImage, String pExtension) {
        String path = "./src/main/java/vista/recursos/UI Elements/" + pImage + pExtension;
        return path;
    }

    private String getSpritePath(String pImage, String pExtension) {
        String path = "./src/main/java/vista/recursos/sprites/" + pImage + pExtension;
        return path;
    }

    private Image resizeImage(String path,int width,int height) {
        Image image = null;
        try {
            image = ImageIO.read(new File(path));//Puede cambiarse por la dirección absoluta
            image = image.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        } catch (IOException e) {
            System.out.println("Something went wrong.");
        }
        return image;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel agregarAntiheroe;
    public javax.swing.JPanel agregarHeroe;
    public javax.swing.JPanel agregarNuevaCiudad;
    private javax.swing.JPanel agregarPersonaje;
    public javax.swing.JPanel agregarVillano;
    public javax.swing.JLabel backBtnAAH;
    public javax.swing.JLabel backBtnAC;
    public javax.swing.JLabel backBtnAH;
    public javax.swing.JLabel backBtnAP;
    public javax.swing.JLabel backBtnAV;
    public javax.swing.JLabel backBtnB;
    public javax.swing.JLabel backBtnC;
    public javax.swing.JLabel backBtnGC;
    public javax.swing.JLabel backBtnGC1;
    public javax.swing.JLabel backBtnSC;
    public javax.swing.JLabel backBtnSP;
    private javax.swing.JPanel banner;
    private javax.swing.JPanel bannerAntiheroe;
    private javax.swing.JPanel bannerConsultas;
    private javax.swing.JPanel bannerHeroe;
    private javax.swing.JPanel bannerVillano;
    private javax.swing.JTextField barraBusqueda;
    public javax.swing.JProgressBar barraProbabilidad;
    private javax.swing.JPanel batalla;
    public javax.swing.JLabel btnAgregarAntiheroe;
    public javax.swing.JLabel btnAgregarAntiheroe2;
    public javax.swing.JLabel btnAgregarHeroe;
    public javax.swing.JLabel btnAgregarImgAntiheroe;
    public javax.swing.JLabel btnAgregarImgAtaqueAH;
    public javax.swing.JLabel btnAgregarImgAtaqueH;
    public javax.swing.JLabel btnAgregarImgAtaqueV;
    public javax.swing.JLabel btnAgregarImgHeroe;
    public javax.swing.JLabel btnAgregarImgVillano;
    public javax.swing.JLabel btnAgregarPersonaje;
    public javax.swing.JLabel btnAgregarVillano;
    public javax.swing.JLabel btnAgregarVillano2;
    private javax.swing.JButton btnBuscar;
    public javax.swing.JLabel btnCargarCiudad;
    public javax.swing.JLabel btnCargarCiudad1;
    public javax.swing.JLabel btnConsultas;
    public javax.swing.JLabel btnCrearAntiheroe;
    public javax.swing.JLabel btnCrearCiudad;
    public javax.swing.JLabel btnCrearHeroe;
    public javax.swing.JLabel btnCrearVillano;
    public javax.swing.JLabel btnEditarCiudad;
    public javax.swing.JLabel btnEmpezarBatalla;
    public javax.swing.JLabel btnFight;
    public javax.swing.JLabel btnGestionCiudad;
    public javax.swing.JLabel btnImagenCiudad;
    public javax.swing.JLabel btnJugar;
    public javax.swing.JLabel btnNuevaCiudad;
    public javax.swing.JLabel btnSeleccionarPersonaje;
    public javax.swing.JComboBox<String> comboboxArchienemigoAH;
    public javax.swing.JComboBox<String> comboboxArchienemigoH;
    public javax.swing.JComboBox<String> comboboxSelecAntiheroeXML;
    public javax.swing.JComboBox<String> comboboxSelecHeroeXML;
    public javax.swing.JComboBox<String> comboboxSelecVillanoXML;
    public javax.swing.JComboBox<String> comboboxTipoVillano;
    private javax.swing.JPanel consultas;
    private javax.swing.JPanel editarCiudad;
    public javax.swing.JLabel escenarioBg;
    public javax.swing.JLabel exitButton;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondoAgregarAntiheroe;
    private javax.swing.JLabel fondoAgregarHeroe;
    private javax.swing.JLabel fondoAgregarHeroe1;
    private javax.swing.JLabel fondoAgregarPersonaje;
    private javax.swing.JLabel fondoAgregarVillano;
    public javax.swing.JLabel fondoAtqAntiheroe;
    public javax.swing.JLabel fondoAtqHeroe;
    public javax.swing.JLabel fondoAtqVillano;
    private javax.swing.JLabel fondoConsultas;
    public javax.swing.JLabel fondoDefAntiheroe;
    public javax.swing.JLabel fondoDefHeroe;
    public javax.swing.JLabel fondoDefVillano;
    private javax.swing.JLabel fondoGestionCiudad;
    private javax.swing.JLabel fondoGestionCiudad1;
    private javax.swing.JLabel fondoGestionCiudad2;
    private javax.swing.JLabel fondoSeleccionarCiudad;
    private javax.swing.JLabel fondoSeleccionarPersonaje;
    private javax.swing.JPanel gestionCiudad;
    public javax.swing.JTextField idSecretaAntiheroe;
    public javax.swing.JTextField idSecretaHeroe;
    public javax.swing.JTextField idSecretaVillano;
    public javax.swing.JLabel imgAntiheroe;
    public javax.swing.JLabel imgAtaqueVillano;
    public javax.swing.JLabel imgAtqAntiheroe;
    public javax.swing.JLabel imgAtqHeroe;
    public javax.swing.JLabel imgAtqHeroeAntiheroe;
    public javax.swing.JLabel imgAtqVillano;
    public javax.swing.JLabel imgBatallaVillano;
    public javax.swing.JLabel imgFight;
    public javax.swing.JLabel imgHeroe;
    public javax.swing.JLabel imgHeroeAntiheroe;
    public javax.swing.JLabel imgVillano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JList<String> listaCiudades;
    private javax.swing.JList<String> listaCiudadesConsulta;
    public javax.swing.JList<String> listaHeroesAntiheroes;
    public javax.swing.JList<String> listaVillanos;
    public javax.swing.JPanel menuPrincipal;
    public javax.swing.JTextField nombreAntiheroe;
    public javax.swing.JTextField nombreCiudad;
    public javax.swing.JTextField nombreHeroe;
    public javax.swing.JTextField nombreVillano;
    private javax.swing.JTabbedPane panelPestañas;
    public javax.swing.JScrollPane pestañaEfectividad;
    private javax.swing.JScrollPane pestañaEventos;
    public javax.swing.JLabel previewImage;
    public javax.swing.JLabel rondas;
    public javax.swing.JLabel rondasGanadasHeroe;
    public javax.swing.JLabel rondasGanadasVillano;
    private javax.swing.JScrollPane scrollPanel;
    public javax.swing.JFileChooser seleccionarArchivoXML;
    public javax.swing.JPanel seleccionarCiudad;
    public javax.swing.JFileChooser seleccionarImagen;
    public javax.swing.JPanel seleccionarPersonaje;
    private javax.swing.JPanel sombraArchienemigoAH;
    private javax.swing.JPanel sombraArchienemigoH;
    private javax.swing.JPanel sombraArchienemigoV;
    private javax.swing.JPanel sombraIdentidadSecretaAH;
    private javax.swing.JPanel sombraIdentidadSecretaH;
    private javax.swing.JPanel sombraIdentidadSecretaV;
    private javax.swing.JPanel sombraNombreAntiheroe;
    private javax.swing.JPanel sombraNombreHeroe;
    private javax.swing.JPanel sombraNombreVillano;
    private javax.swing.JPanel sombraSeleccionarAntiheroeXML;
    private javax.swing.JPanel sombraSeleccionarHeroeXML;
    private javax.swing.JPanel sombraSeleccionarVillanoXML;
    private javax.swing.JTable tablaEventos;
    private javax.swing.JLabel txtAgregarAntiheroe;
    private javax.swing.JLabel txtAgregarCiudad;
    private javax.swing.JLabel txtAgregarCiudad1;
    private javax.swing.JLabel txtAgregarHeroe;
    private javax.swing.JLabel txtAgregarImgAntiheroe;
    private javax.swing.JLabel txtAgregarImgAtaqueAH;
    private javax.swing.JLabel txtAgregarImgAtaqueH;
    private javax.swing.JLabel txtAgregarImgAtaqueV;
    private javax.swing.JLabel txtAgregarImgHeroe;
    private javax.swing.JLabel txtAgregarImgVillano;
    private javax.swing.JLabel txtAgregarPersonajes;
    private javax.swing.JLabel txtAgrergarVillano;
    private javax.swing.JLabel txtArchienemigoAH;
    private javax.swing.JLabel txtArchienemigoH;
    private javax.swing.JLabel txtCargarCiudad;
    private javax.swing.JLabel txtCargarCiudad1;
    private javax.swing.JLabel txtCargarImgCiudad;
    private javax.swing.JLabel txtConsultas;
    private javax.swing.JLabel txtCrearAntiheroe;
    private javax.swing.JLabel txtCrearCiudad;
    private javax.swing.JLabel txtCrearHeroe;
    private javax.swing.JLabel txtCrearVillano;
    private javax.swing.JLabel txtDatosHeroe;
    private javax.swing.JLabel txtDatosHeroe1;
    private javax.swing.JLabel txtDatosVillano;
    private javax.swing.JLabel txtEditarCiudad;
    private javax.swing.JLabel txtEditarCiudad1;
    private javax.swing.JLabel txtEfectividad;
    private javax.swing.JLabel txtEmpezarBatalla;
    private javax.swing.JLabel txtGestionCiudad;
    private javax.swing.JLabel txtHeroes;
    private javax.swing.JLabel txtIdentidadAntiheroe;
    private javax.swing.JLabel txtIdentidadHeroe;
    private javax.swing.JLabel txtIdentidadVillano;
    private javax.swing.JLabel txtJugar;
    private javax.swing.JLabel txtMenuPrincipal;
    private javax.swing.JLabel txtMenuPrincipal1;
    private javax.swing.JLabel txtNombreAtiheroe;
    private javax.swing.JLabel txtNombreCiudad;
    private javax.swing.JLabel txtNombreHeroe;
    private javax.swing.JLabel txtNombreVillano;
    private javax.swing.JLabel txtRondasGanadasHeroeAntiheroe;
    private javax.swing.JLabel txtRondasGanadasVillano;
    private javax.swing.JLabel txtSeleccionarHeroeXML;
    private javax.swing.JLabel txtSeleccionarHeroeXML1;
    private javax.swing.JLabel txtSeleccionarHeroeXML2;
    private javax.swing.JLabel txtSeleccionarMapa;
    private javax.swing.JLabel txtTipoVillano;
    private javax.swing.JLabel txtVillanos;
    // End of variables declaration//GEN-END:variables
}
